# Generated by Django 2.1.5 on 2019-01-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    """Alter DigitalFile.datemodified: CharField <-> DateTimeField.

    ISO 8601 format (e.g.: 2003-09-10T21:22:30) works forwards and backwards
    with the default Django serialization but no other formats have been tested.
    """

    dependencies = [("scope", "0002_initial_data")]

    operations = [
        migrations.AlterField(
            model_name="digitalfile",
            name="datemodified",
            field=models.DateTimeField(blank=True, null=True),
        )
    ]
