# Generated by Django 2.2.12 on 2020-04-22 17:58

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("scope", "0002_initial_data")]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=jsonfield.fields.JSONField(max_length=500),
        )
    ]
