# Generated by Django 2.1.7 on 2019-03-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("dips", "0003_alter_digitalfile_datemodified")]

    operations = [
        migrations.AlterField(
            model_name="digitalfile",
            name="puid",
            field=models.CharField(blank=True, max_length=200),
        )
    ]
