# Generated by Django 2.1.7 on 2019-03-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0004_alter_digitalfile_puid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dublincore',
            name='language',
            field=models.CharField(blank=True, max_length=200, verbose_name='language'),
        ),
    ]
