# Generated by Django 2.1.7 on 2019-04-30 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("dips", "0006_alter_dip")]

    operations = [migrations.DeleteModel(name="TaskResult")]
