# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('creator', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('contributor', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=21, null=True)),
                ('dctype', models.CharField(max_length=200, null=True)),
                ('dcformat', models.TextField(null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('coverage', models.CharField(max_length=200, null=True)),
                ('rights', models.CharField(max_length=200, null=True)),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalFile',
            fields=[
                ('uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('filepath', models.TextField()),
                ('fileformat', models.CharField(max_length=200)),
                ('formatversion', models.CharField(max_length=200, null=True)),
                ('size_bytes', models.IntegerField()),
                ('size_human', models.CharField(max_length=10, null=True)),
                ('datemodified', models.CharField(max_length=30, null=True)),
                ('puid', models.CharField(max_length=11, null=True)),
                ('amdsec', models.CharField(max_length=12)),
                ('hashtype', models.CharField(max_length=7)),
                ('hashvalue', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DIP',
            fields=[
                ('identifier', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('creator', models.CharField(max_length=200, null=True)),
                ('subject', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('contributor', models.CharField(max_length=200, null=True)),
                ('date', models.CharField(max_length=21, null=True)),
                ('dctype', models.CharField(max_length=200, null=True)),
                ('dcformat', models.TextField(null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('language', models.CharField(max_length=20, null=True)),
                ('coverage', models.CharField(max_length=200, null=True)),
                ('rights', models.CharField(max_length=200, null=True)),
                ('metsfile', models.FileField(default=None, null=True, upload_to='')),
                ('objectszip', models.FileField(default=None, null=True, upload_to='')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('ispartof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dips', to='dips.Collection')),
            ],
        ),
        migrations.CreateModel(
            name='PREMISEvent',
            fields=[
                ('uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('eventtype', models.CharField(max_length=200, null=True)),
                ('datetime', models.CharField(max_length=50, null=True)),
                ('detail', models.TextField(null=True)),
                ('outcome', models.TextField(null=True)),
                ('detailnote', models.TextField(null=True)),
                ('digitalfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premis_events', to='dips.DigitalFile')),
            ],
        ),
        migrations.AddField(
            model_name='digitalfile',
            name='dip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_files', to='dips.DIP'),
        ),
        migrations.AddField(
            model_name='collection',
            name='ispartof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='dips.Department'),
        ),
    ]
