# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0002_auto_20171018_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='dcformat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dip',
            name='dcformat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premisevent',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premisevent',
            name='detailnote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premisevent',
            name='outcome',
            field=models.TextField(blank=True, null=True),
        ),
    ]
