# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0003_modify_user_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='DublinCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('creator', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('contributor', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=21)),
                ('type', models.CharField(blank=True, max_length=200)),
                ('format', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('coverage', models.CharField(blank=True, max_length=200)),
                ('rights', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='dip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dip',
            name='identifier',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='collection',
            name='dc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dips.DublinCore'),
        ),
        migrations.AddField(
            model_name='dip',
            name='dc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dips.DublinCore'),
        ),
    ]
