# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0003_auto_20171018_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalfile',
            name='formatversion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
