# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0004_auto_20171018_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
