# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 10:32
from __future__ import unicode_literals

from django.db import migrations


def create_and_relate_dc(resource, dc_model):
    """Create DublinCore from Collection or DIP and relate them."""
    resource.dc = dc_model.objects.create(
        identifier=resource.identifier,
        title=resource.title,
        creator=resource.creator,
        subject=resource.subject,
        description=resource.description or '',
        publisher=resource.publisher,
        contributor=resource.contributor,
        date=resource.date,
        type=resource.dctype,
        format=resource.dcformat or '',
        source=resource.source,
        language=resource.language,
        coverage=resource.coverage,
        rights=resource.rights,
    )
    resource.save()


def copy_dc_metadata(apps, schema_editor):
    """Copy DC metadata from Collections and DIPs to new DC table."""
    Collection = apps.get_model('dips', 'Collection')
    DIP = apps.get_model('dips', 'DIP')
    DublinCore = apps.get_model('dips', 'DublinCore')
    for collection in Collection.objects.all().iterator():
        create_and_relate_dc(resource=collection, dc_model=DublinCore)
    for dip in DIP.objects.all().iterator():
        create_and_relate_dc(resource=dip, dc_model=DublinCore)


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0004_auto_20180623_0114'),
    ]

    operations = [
        migrations.RunPython(copy_dc_metadata),
    ]
