# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models


def fix_foreing_keys(apps, schema_editor):
    """Update foreing keys to reference ids instead of identifiers."""
    Collection = apps.get_model('dips', 'Collection')
    DIP = apps.get_model('dips', 'DIP')
    DigitalFile = apps.get_model('dips', 'DigitalFile')
    for dip in DIP.objects.all().iterator():
        collection = Collection.objects.get(identifier=dip.ispartof_id)
        dip.ispartof_id = collection.id
        dip.save()
    for digital_file in DigitalFile.objects.all().iterator():
        dip = DIP.objects.get(identifier=digital_file.dip_id)
        digital_file.dip_id = dip.id
        digital_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0005_copy_dc_metadata'),
    ]

    operations = [
        migrations.RunPython(fix_foreing_keys),
        migrations.AlterField(
            model_name='dip',
            name='ispartof',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='dips', to='dips.Collection'),
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='dip',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='digital_files', to='dips.DIP'),
        ),
    ]
