# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0005_auto_20171018_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
