# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-23 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0006_fix_foreing_keys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dip',
            old_name='ispartof',
            new_name='collection',
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='size_bytes',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='digitalfile',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='premisevent',
            name='uuid',
            field=models.CharField(max_length=36, primary_key=True, serialize=False),
        ),
    ]
