# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0006_auto_20171018_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='ispartof',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
