# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0007_auto_20180623_0227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='date',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='dcformat',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='dctype',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='language',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='source',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='date',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='dcformat',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='dctype',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='description',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='language',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='source',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='dip',
            name='title',
        ),
    ]
