# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-21 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0008_remove_dip_metsfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dip',
            name='objectszip',
            field=models.FileField(upload_to=''),
        ),
    ]
