# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0008_auto_20180624_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='link',
            field=models.URLField(blank=True, verbose_name='finding aid'),
        ),
        migrations.AlterField(
            model_name='dip',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dips', to='dips.Collection', verbose_name='collection'),
        ),
        migrations.AlterField(
            model_name='dip',
            name='objectszip',
            field=models.FileField(upload_to='', verbose_name='objects zip file'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='contributor',
            field=models.CharField(blank=True, max_length=200, verbose_name='contributor'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='coverage',
            field=models.CharField(blank=True, max_length=200, verbose_name='coverage'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='creator',
            field=models.CharField(blank=True, max_length=200, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='date',
            field=models.CharField(blank=True, max_length=21, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='format',
            field=models.TextField(blank=True, verbose_name='format'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='identifier',
            field=models.CharField(max_length=50, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='language',
            field=models.CharField(blank=True, max_length=20, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='publisher',
            field=models.CharField(blank=True, max_length=200, verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='rights',
            field=models.CharField(blank=True, max_length=200, verbose_name='rights'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='source'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='subject',
            field=models.CharField(blank=True, max_length=200, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='dublincore',
            name='type',
            field=models.CharField(blank=True, max_length=200, verbose_name='type'),
        ),
    ]
