# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0010_add_viewers_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='dip',
            name='import_status',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='dip',
            name='import_task_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
