# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-31 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0001_initial'),
        ('dips', '0011_auto_20180729_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskResult',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('django_celery_results.taskresult',),
        ),
    ]
