# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.encoder
import jsonfield.fields

from dips.models import DublinCore, Setting


def add_initial_settings(apps, schema_editor):
    # Enabled DC fields
    Setting.objects.create(
        name='enabled_optional_dc_fields',
        value=list(DublinCore.get_optional_fields().keys()),
    )
    # Hide empty DC fields
    Setting.objects.create(
        name='hide_empty_dc_fields',
        value=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dips', '0012_taskresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('value', jsonfield.fields.JSONField(dump_kwargs={'cls': jsonfield.encoder.JSONEncoder, 'separators': (',', ':')}, load_kwargs={}, max_length=500)),
            ],
        ),
        migrations.RunPython(add_initial_settings),
    ]
